definitions:
  controller.GetIngredientsResponse:
    properties:
      ingredients:
        items:
          $ref: '#/definitions/entity.Ingredient'
        type: array
    type: object
  entity.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  entity.Ingredient:
    properties:
      id:
        type: string
      name:
        type: string
      weight:
        type: integer
    type: object
info:
  contact: {}
  description: ref
  title: ref
  version: "1.0"
paths:
  /ingredients:
    get:
      consumes:
      - application/json
      parameters:
      - description: min
        in: query
        name: min
        type: integer
      - description: max
        in: query
        name: max
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetIngredientsResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: 全素材取得 API
      tags:
      - Ingredient
swagger: "2.0"
