name: build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_LOCATION: ${{ secrets.GCP_LOCATION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '273.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker-compose up

      - name: Access endpoint
        run: curl -X 'GET' 'localhost:8080/api/v1/ingredients'
