name: Cloud Run

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build a backend docker image
        run: |
          cd ./backend/
          docker build --tag ref:staging .

